<?php
/**
 * @copyright   Copyright (c) Vendic B.V https://vendic.nl/
 */

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var GuestChecker $guestChecker */
/** @var Rewards $rewards */
/** @var CheckoutConfig $checkoutConfig */
/** @var SpendPoints $magewire */
/** @var HeroiconsOutline $heroIcons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Vendic\HyvaCheckoutMirasvitRewards\Magewire\Checkout\SpendPoints;
use Vendic\HyvaCheckoutMirasvitRewards\ViewModel\CheckoutConfig;
use Vendic\HyvaCheckoutMirasvitRewards\ViewModel\GuestChecker;
use Vendic\HyvaCheckoutMirasvitRewards\ViewModel\Rewards;

$guestChecker = $viewModels->require(GuestChecker::class);
$heroIcons = $viewModels->require(HeroiconsOutline::class);
$rewards = $viewModels->require(Rewards::class);
$checkoutConfig = $viewModels->require(CheckoutConfig::class);
$maxSpendPoints = $rewards->getMaxSpendPoints();
$balancePoints = $rewards->getBalancePoints();
$isGuest = $guestChecker->isCustomerGuest();
$pointUnitName = $checkoutConfig->getPointUnitName();
?>
<div class="pt-5" x-data="mirasvitRewardsSpendPoints">
    <button type="button"
            class="font-semibold flex items-center"
            aria-controls="spend-points-details"
            x-on:click="toggleExpanded"
            x-bind:aria-expanded="expanded">
        <span class="mr-0.5">
            <?= $escaper->escapeHtml(__('Use %1', [$pointUnitName])) ?>
        </span>
        <?= /* @noEscape  */ $heroIcons->chevronDownHtml('inline-block w-4 h-4') ?>
    </button>
    <?php if ($isGuest): ?>
        <span id="spend-points-details" class="pt-1 block text-sm text-gray-500" x-show="expanded" x-cloak>
            <?= $escaper->escapeHtml($checkoutConfig->getCheckoutNotification()) ?>
        </span>
    <?php else: ?>
    <form id="spend-points-details" class="pt-1" x-show="expanded" x-cloak>
        <p class="text-sm text-gray-500 mb-2">
            <?= $escaper->escapeHtml(
                __('You have %1 %2 available.', [$balancePoints, $pointUnitName])
            ) ?>
        </p>
        <label for="spend-points" class="sr-only">
            <?= $escaper->escapeHtml(__('Enter amount of points to spend')) ?>
        </label>
        <input wire:model.debounce.500ms="spend"
               value="<?= $escaper->escapeHtml($magewire->spend) ?>"
               type="number"
               min="0"
               max="<?= $escaper->escapeHtmlAttr($maxSpendPoints) ?>"
               id="spend-points"
               class="form-input w-full"><br>
        <span class="block mt-1 text-sm text-gray-500">
            <?= $escaper->escapeHtml(
                __('Use maximum %1 %2.', [$maxSpendPoints, $pointUnitName])
            ) ?>
        </span>
    </form>
    <?php endif; ?>
</div>
